repos:
- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    language: system
    pass_filenames: false
    always_run: true

  - id: test
    name: test
    entry: make test
    language: system
    pass_filenames: false
    always_run: true

