version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - lk_user_mongo:/data/db
    ports:
    - '27017:27017'

volumes:
  lk_user_mongo:
